Update Dockerfile
- Pick up the latest Alpine. Alpine 3.3 has an expired Let's Encrypt
  root certificate [^1], and "curl https://cilium.io/" fails with an
  error: "curl: (60) SSL certificate problem: certificate has expired"
- Update the URL to download netperf-2.7.0 from. The FTP site no longer
  hosts the netperf-2.7.0.tar.gz file.
- Pass CFLAGS=-fcommon to make to fix a compilation error [^2].

[^1]: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/
[^2]: https://github.com/HewlettPackard/netperf/issues/59

Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>